# Include modules
import os
print("CWD=",os.getcwd())
configfile: "config/config.yaml"


module af3:
    snakefile: "rules/AF3.smk"
    config:
        config
module foldseek:
    snakefile: "rules/FOLDSEEK.smk"
    config:
        config
use rule * from af3
use rule * from foldseek

# Define a rule that triggers both modules
rule all:
    input:
        rules.foldseek_all.input,
    default_target: True