executor: slurm

default-resources:
    slurm_partition: "vds"
    slurm_account: "vds"

set-resources:
    AF3_DATA:
        slurm_partition: "vds"
        nodes: 1
        runtime: 10000
        cpus_per_task: 16
    AF3_INFERENCE:
        slurm_partition: "vds"
        slurm_extra: "'--gpus-per-node=1'"
        nodes: 1
        runtime: 10000
        mem_mb: 256000