#input_csv: example/pulldown.csv # pulldown
input_csv: example/gabriel_virtual_drug_screen/virtual_drug_screen_df.csv # virtual drug screen
#input_csv: example/all_vs_all.csv # all-vs-all
output_dir: output
#mode: pulldown # pulldown
mode: virtual-drug-screen # virtual drug screen
n_splits: 4
#mode: all-vs-all # all-vs-all
af3_flags:
  --af3_container: sif
  --db_dir: db_dir
  --model_dir: params
